# 1.1.8. Generarar dataset de metricas

La idea consiste en generar conjuntos de datos intermedios que contengan métricas para las existencias ovinas, los kilogramos de lana, la finura y el rinde. Estos datos intermedios nos permitirán completar el conjunto de datos final de manera más estructurada utilizando estas métricas.

In [1]:
import numpy as np
import pandas as pd

Vamos a empezar con los datos para las existencias.

In [11]:
datos = pd.read_csv("actualizando_dataset - dataset_nuevos_porcentajes_existencias.csv")
datos

,fecha,provincia,departamento,%_carneros,%_ovejas,%_borregos,%_capones,%_corderos_corderas,kilos_animal,finura,rinde
0,2013-12-31,CHUBUT,BIEDMA,2.28,41.05,15.81,19.39,21.47,3.16,19.80,55.00
1,2014-12-31,CHUBUT,BIEDMA,2.03,38.60,18.60,18.73,22.03,3.24,19.22,58.86
2,2013-12-31,CHUBUT,CUSHAMEN,2.70,48.83,14.92,10.01,23.55,2.73,20.04,57.47
3,2014-12-31,CHUBUT,CUSHAMEN,2.42,44.60,15.30,10.95,26.72,3.34,19.74,63.35
4,2013-12-31,CHUBUT,FLORENTINO AMEGHINO,2.38,39.30,18.77,14.61,24.94,2.85,19.30,57.75
5,2014-12-31,CHUBUT,FLORENTINO AMEGHINO,2.56,40.60,16.21,14.82,25.80,2.73,19.53,60.37
6,2013-12-31,CHUBUT,FUTALEUFU,3.20,49.78,12.70,12.78,21.53,3.14,21.60,63.90
7,2014-12-31,CHUBUT,FUTALEUFU,3.14,46.98,12.60,10.83,26.44,3.30,21.55,62.93
8,2013-12-31,CHUBUT,GAIMAN,2.43,51.81,11.90,14.89,18.97,3.41,20.80,56.20
9,2014-12-31,CHUBUT,GAIMAN,2.47,45.06,13.90,13.20,25.37,3.19,20.39,55.06
10,2013-12-31,CHUBUT,LANGUIÑEO,3.02,40.05,18.93,17.62,20.38,3.32,20.00,55.40
11,2015-12-31,CHUBUT,LANGUIÑEO,2.78,39.64,17.58,18.51,21.49,3.54,19.86,60.94
12,2013-12-31,CHUBUT,PASO DE INDIOS,2.57,47.14,14.45,17.79,18.04,3.52,20.20,52.60
13,2014-12-31,CHUBUT,PASO DE INDIOS,2.60,43.35,14.84,17.94,21.28,3.41,19.92,54.19
14,2013-12-31,CHUBUT,RAWSON,2.87,44.78,14.90,17.18,20.27,3.46,20.30,55.67
15,2014-12-31,CHUBUT,RAWSON,2.80,42.44,14.43,17.12,23.21,3.23,19.78,61.22
16,2013-12-31,CHUBUT,RIO SENGUERR,2.52,42.83,18.06,14.02,22.56,3.25,20.25,55.86
17,2014-12-31,CHUBUT,RIO SENGUERR,2.78,44.05,16.18,14.88,22.11,3.36,20.10,59.01
18,2013-12-31,CHUBUT,SARMIENTO,3.30,47.20,14.49,16.89,18.12,3.66,20.73,49.13
19,2014-12-31,CHUBUT,SARMIENTO,2.89,43.94,15.14,17.55,20.48,3.81,19.92,48.21
20,2013-12-31,CHUBUT,TEHUELCHES,3.02,39.55,17.52,19.08,20.82,3.63,20.05,60.07
21,2014-12-31,CHUBUT,TEHUELCHES,3.12,39.96,17.04,20.42,19.45,3.51,19.41,61.21
22,2013-12-31,CHUBUT,TELSEN,2.72,43.55,16.59,21.55,15.59,3.50,20.01,51.90
23,2014-12-31,CHUBUT,TELSEN,2.53,42.68,16.55,16.26,21.98,3.62,19.79,54.01

In [13]:
datos_agrupado = datos.groupby("departamento").agg({
    "%_carneros": ["mean", "std", "min", "max"],
    "%_ovejas": ["mean", "std", "min", "max"],
    "%_borregos": ["mean", "std", "min", "max"],
    "%_capones": ["mean", "std", "min", "max"],
    "%_corderos_corderas": ["mean", "std", "min", "max"],
})

In [14]:
datos_agrupado.stack()

                          %_carneros   %_ovejas  %_borregos  %_capones  \
departamento
BIEDMA              mean    2.155000  39.825000   17.205000  19.060000
                    std     0.176777   1.732412    1.972828   0.466690
                    min     2.030000  38.600000   15.810000  18.730000
                    max     2.280000  41.050000   18.600000  19.390000
CUSHAMEN            mean    2.560000  46.715000   15.110000  10.480000
                    std     0.197990   2.991062    0.268701   0.664680
                    min     2.420000  44.600000   14.920000  10.010000
                    max     2.700000  48.830000   15.300000  10.950000
FLORENTINO AMEGHINO mean    2.470000  39.950000   17.490000  14.715000
                    std     0.127279   0.919239    1.810193   0.148492
                    min     2.380000  39.300000   16.210000  14.610000
                    max     2.560000  40.600000   18.770000  14.820000
FUTALEUFU           mean    3.170000  48.380000   12.650000  11.805000
                    std     0.042426   1.979899    0.070711   1.378858
                    min     3.140000  46.980000   12.600000  10.830000
                    max     3.200000  49.780000   12.700000  12.780000
GAIMAN              mean    2.450000  48.435000   12.900000  14.045000
                    std     0.028284   4.772971    1.414214   1.195010
                    min     2.430000  45.060000   11.900000  13.200000
                    max     2.470000  51.810000   13.900000  14.890000
LANGUIÑEO           mean    2.900000  39.845000   18.255000  18.065000
                    std     0.169706   0.289914    0.954594   0.629325
                    min     2.780000  39.640000   17.580000  17.620000
                    max     3.020000  40.050000   18.930000  18.510000
PASO DE INDIOS      mean    2.585000  45.245000   14.645000  17.865000
                    std     0.021213   2.679935    0.275772   0.106066
                    min     2.570000  43.350000   14.450000  17.790000
                    max     2.600000  47.140000   14.840000  17.940000
RAWSON              mean    2.835000  43.610000   14.665000  17.150000
                    std     0.049497   1.654630    0.332340   0.042426
                    min     2.800000  42.440000   14.430000  17.120000
                    max     2.870000  44.780000   14.900000  17.180000
RIO SENGUERR        mean    2.650000  43.440000   17.120000  14.450000
                    std     0.183848   0.862670    1.329361   0.608112
                    min     2.520000  42.830000   16.180000  14.020000
                    max     2.780000  44.050000   18.060000  14.880000
SARMIENTO           mean    3.095000  45.570000   14.815000  17.220000
                    std     0.289914   2.305168    0.459619   0.466690
                    min     2.890000  43.940000   14.490000  16.890000
                    max     3.300000  47.200000   15.140000  17.550000
TEHUELCHES          mean    3.070000  39.755000   17.280000  19.750000
                    std     0.070711   0.289914    0.339411   0.947523
                    min     3.020000  39.550000   17.040000  19.080000
                    max     3.120000  39.960000   17.520000  20.420000
TELSEN              mean    2.625000  43.115000   16.570000  18.905000
                    std     0.134350   0.615183    0.028284   3.740595
                    min     2.530000  42.680000   16.550000  16.260000
                    max     2.720000  43.550000   16.590000  21.550000

                          %_corderos_corderas
departamento
BIEDMA              mean            21.750000
                    std              0.395980
                    min             21.470000
                    max             22.030000
CUSHAMEN            mean            25.135000
                    std              2.241528
                    min             23.550000
                    max             26.720000
FLORENTINO AMEGHINO mean            25.370000
                    std              0.608112
                    min             24.940000
                    max             25.800000
FUTALEUFU           mean            23.985000
                    std              3.471894
                    min             21.530000
                    max             26.440000
GAIMAN              mean            22.170000
                    std              4.525483
                    min             18.970000
                    max             25.370000
LANGUIÑEO           mean            20.935000
                    std              0.784889
                    min             20.380000
                    max             21.490000
PASO DE INDIOS      mean            19.660000
                    std              2.291026
                    min             18.040000
                    max             21.280000
RAWSON              mean            21.740000
                    std              2.078894
                    min             20.270000
                    max             23.210000
RIO SENGUERR        mean            22.335000
                    std              0.318198
                    min             22.110000
                    max             22.560000
SARMIENTO           mean            19.300000
                    std              1.668772
                    min             18.120000
                    max             20.480000
TEHUELCHES          mean            20.135000
                    std              0.968736
                    min             19.450000
                    max             20.820000
TELSEN              mean            18.785000
                    std              4.518412
                    min             15.590000
                    max             21.980000

In [16]:
df_resultante = datos_agrupado.stack().reset_index()
df_resultante.rename(columns={'level_1':'metrica',
                   '%_carneros': 'carneros',
                   '%_ovejas': 'ovejas',
                   '%_borregos':'borregos',
                   '%_capones': 'capones',
                   '%_corderos_corderas': 'corderos_corderas'
                  }, inplace=True)
df_resultante

,departamento,metrica,carneros,ovejas,borregos,capones,corderos_corderas
0,BIEDMA,mean,2.155000,39.825000,17.205000,19.060000,21.750000
1,BIEDMA,std,0.176777,1.732412,1.972828,0.466690,0.395980
2,BIEDMA,min,2.030000,38.600000,15.810000,18.730000,21.470000
3,BIEDMA,max,2.280000,41.050000,18.600000,19.390000,22.030000
4,CUSHAMEN,mean,2.560000,46.715000,15.110000,10.480000,25.135000
5,CUSHAMEN,std,0.197990,2.991062,0.268701,0.664680,2.241528
6,CUSHAMEN,min,2.420000,44.600000,14.920000,10.010000,23.550000
7,CUSHAMEN,max,2.700000,48.830000,15.300000,10.950000,26.720000
8,FLORENTINO AMEGHINO,mean,2.470000,39.950000,17.490000,14.715000,25.370000
9,FLORENTINO AMEGHINO,std,0.127279,0.919239,1.810193,0.148492,0.608112
10,FLORENTINO AMEGHINO,min,2.380000,39.300000,16.210000,14.610000,24.940000
11,FLORENTINO AMEGHINO,max,2.560000,40.600000,18.770000,14.820000,25.800000
12,FUTALEUFU,mean,3.170000,48.380000,12.650000,11.805000,23.985000
13,FUTALEUFU,std,0.042426,1.979899,0.070711,1.378858,3.471894
14,FUTALEUFU,min,3.140000,46.980000,12.600000,10.830000,21.530000
15,FUTALEUFU,max,3.200000,49.780000,12.700000,12.780000,26.440000
16,GAIMAN,mean,2.450000,48.435000,12.900000,14.045000,22.170000
17,GAIMAN,std,0.028284,4.772971,1.414214,1.195010,4.525483
18,GAIMAN,min,2.430000,45.060000,11.900000,13.200000,18.970000
19,GAIMAN,max,2.470000,51.810000,13.900000,14.890000,25.370000
20,LANGUIÑEO,mean,2.900000,39.845000,18.255000,18.065000,20.935000
21,LANGUIÑEO,std,0.169706,0.289914,0.954594,0.629325,0.784889
22,LANGUIÑEO,min,2.780000,39.640000,17.580000,17.620000,20.380000
23,LANGUIÑEO,max,3.020000,40.050000,18.930000,18.510000,21.490000
24,PASO DE INDIOS,mean,2.585000,45.245000,14.645000,17.865000,19.660000
25,PASO DE INDIOS,std,0.021213,2.679935,0.275772,0.106066,2.291026
26,PASO DE INDIOS,min,2.570000,43.350000,14.450000,17.790000,18.040000
27,PASO DE INDIOS,max,2.600000,47.140000,14.840000,17.940000,21.280000
28,RAWSON,mean,2.835000,43.610000,14.665000,17.150000,21.740000
29,RAWSON,std,0.049497,1.654630,0.332340,0.042426,2.078894
30,RAWSON,min,2.800000,42.440000,14.430000,17.120000,20.270000
31,RAWSON,max,2.870000,44.780000,14.900000,17.180000,23.210000
32,RIO SENGUERR,mean,2.650000,43.440000,17.120000,14.450000,22.335000
33,RIO SENGUERR,std,0.183848,0.862670,1.329361,0.608112,0.318198
34,RIO SENGUERR,min,2.520000,42.830000,16.180000,14.020000,22.110000
35,RIO SENGUERR,max,2.780000,44.050000,18.060000,14.880000,22.560000
36,SARMIENTO,mean,3.095000,45.570000,14.815000,17.220000,19.300000
37,SARMIENTO,std,0.289914,2.305168,0.459619,0.466690,1.668772
38,SARMIENTO,min,2.890000,43.940000,14.490000,16.890000,18.120000
39,SARMIENTO,max,3.300000,47.200000,15.140000,17.550000,20.480000
40,TEHUELCHES,mean,3.070000,39.755000,17.280000,19.750000,20.135000
41,TEHUELCHES,std,0.070711,0.289914,0.339411,0.947523,0.968736
42,TEHUELCHES,min,3.020000,39.550000,17.040000,19.080000,19.450000
43,TEHUELCHES,max,3.120000,39.960000,17.520000,20.420000,20.820000
44,TELSEN,mean,2.625000,43.115000,16.570000,18.905000,18.785000
45,TELSEN,std,0.134350,0.615183,0.028284,3.740595,4.518412
46,TELSEN,min,2.530000,42.680000,16.550000,16.260000,15.590000
47,TELSEN,max,2.720000,43.550000,16.590000,21.550000,21.980000

Por último, guardamos el DataFrame como archivo CSV.

In [ ]:
df_resultante.to_csv("nuevo_porcentajes_existencias.csv", index=False)

Continuamos con los datos para la lana.

In [2]:
datos = pd.read_csv("actualizando_dataset - dataset_nuevos_%_lana.csv")
datos

         fecha provincia departamento  kilos_animal
0   2012-12-31    CHUBUT       BIEDMA          3.61
1   2013-12-31    CHUBUT       BIEDMA          3.16
2   2014-12-31    CHUBUT       BIEDMA          3.24
3   2006-12-31    CHUBUT     CUSHAMEN          3.55
4   2007-12-31    CHUBUT     CUSHAMEN          3.42
..         ...       ...          ...           ...
73  2010-12-31    CHUBUT       TELSEN          3.67
74  2011-12-31    CHUBUT       TELSEN          3.92
75  2012-12-31    CHUBUT       TELSEN          3.81
76  2013-12-31    CHUBUT       TELSEN          3.50
77  2014-12-31    CHUBUT       TELSEN          3.62

[78 rows x 4 columns]

In [3]:
datos_agrupado = datos.groupby("departamento").agg({
    "kilos_animal": ["mean", "std", "min", "max"],
})

In [4]:
datos_agrupado.stack()

                          kilos_animal
departamento
BIEDMA              mean      3.336667
                    std       0.240069
                    min       3.160000
                    max       3.610000
CUSHAMEN            mean      3.407500
                    std       0.295284
                    min       2.730000
                    max       3.690000
FLORENTINO AMEGHINO mean      3.286667
                    std       0.430473
                    min       2.730000
                    max       3.690000
FUTALEUFU           mean      3.648750
                    std       0.655274
                    min       2.990000
                    max       5.090000
GAIMAN              mean      3.440000
                    std       0.153716
                    min       3.190000
                    max       3.720000
LANGUIÑEO           mean      3.483333
                    std       0.143643
                    min       3.320000
                    max       3.590000
PASO DE INDIOS      mean      3.568333
                    std       0.179490
                    min       3.410000
                    max       3.910000
RAWSON              mean      3.441250
                    std       0.178920
                    min       3.230000
                    max       3.710000
RIO SENGUERR        mean      3.625000
                    std       0.230403
                    min       3.250000
                    max       3.880000
SARMIENTO           mean      3.713750
                    std       0.224750
                    min       3.230000
                    max       3.900000
TEHUELCHES          mean      3.758333
                    std       0.161173
                    min       3.510000
                    max       3.940000
TELSEN              mean      3.665000
                    std       0.175129
                    min       3.470000
                    max       3.920000

In [6]:
df_resultante = datos_agrupado.stack().reset_index()
df_resultante.rename(columns={'level_1':'metrica',}, inplace=True)
df_resultante

           departamento metrica  kilos_animal
0                BIEDMA    mean      3.336667
1                BIEDMA     std      0.240069
2                BIEDMA     min      3.160000
3                BIEDMA     max      3.610000
4              CUSHAMEN    mean      3.407500
5              CUSHAMEN     std      0.295284
6              CUSHAMEN     min      2.730000
7              CUSHAMEN     max      3.690000
8   FLORENTINO AMEGHINO    mean      3.286667
9   FLORENTINO AMEGHINO     std      0.430473
10  FLORENTINO AMEGHINO     min      2.730000
11  FLORENTINO AMEGHINO     max      3.690000
12            FUTALEUFU    mean      3.648750
13            FUTALEUFU     std      0.655274
14            FUTALEUFU     min      2.990000
15            FUTALEUFU     max      5.090000
16               GAIMAN    mean      3.440000
17               GAIMAN     std      0.153716
18               GAIMAN     min      3.190000
19               GAIMAN     max      3.720000
20            LANGUIÑEO    mean      3.483333
21            LANGUIÑEO     std      0.143643
22            LANGUIÑEO     min      3.320000
23            LANGUIÑEO     max      3.590000
24       PASO DE INDIOS    mean      3.568333
25       PASO DE INDIOS     std      0.179490
26       PASO DE INDIOS     min      3.410000
27       PASO DE INDIOS     max      3.910000
28               RAWSON    mean      3.441250
29               RAWSON     std      0.178920
30               RAWSON     min      3.230000
31               RAWSON     max      3.710000
32         RIO SENGUERR    mean      3.625000
33         RIO SENGUERR     std      0.230403
34         RIO SENGUERR     min      3.250000
35         RIO SENGUERR     max      3.880000
36            SARMIENTO    mean      3.713750
37            SARMIENTO     std      0.224750
38            SARMIENTO     min      3.230000
39            SARMIENTO     max      3.900000
40           TEHUELCHES    mean      3.758333
41           TEHUELCHES     std      0.161173
42           TEHUELCHES     min      3.510000
43           TEHUELCHES     max      3.940000
44               TELSEN    mean      3.665000
45               TELSEN     std      0.175129
46               TELSEN     min      3.470000
47               TELSEN     max      3.920000

Por último, guardamos el DataFrame como archivo CSV.

In [ ]:
df_resultante.to_csv("nuevo_porcentajes_lana.csv", index=False)

Ahora toca hacer lo mismo para la finura y el rinde.

In [7]:
datos = pd.read_csv("actualizando_dataset - dataset_nuevos_%_f_r.csv")
datos

         fecha provincia         departamento  finura  rinde
0   2013-12-31    CHUBUT               BIEDMA   19.80  55.00
1   2014-12-31    CHUBUT               BIEDMA   19.22  58.86
2   2013-12-31    CHUBUT             CUSHAMEN   20.04  57.47
3   2014-12-31    CHUBUT             CUSHAMEN   19.74  63.35
4   2013-12-31    CHUBUT  FLORENTINO AMEGHINO   19.30  57.75
5   2014-12-31    CHUBUT  FLORENTINO AMEGHINO   19.53  60.37
6   2013-12-31    CHUBUT            FUTALEUFU   21.60  63.90
7   2014-12-31    CHUBUT            FUTALEUFU   20.27  63.13
8   2013-12-31    CHUBUT               GAIMAN   20.80  56.20
9   2014-12-31    CHUBUT               GAIMAN   20.39  55.06
10  2013-12-31    CHUBUT            LANGUIÑEO   20.00  55.40
11  2015-12-31    CHUBUT            LANGUIÑEO   19.86  60.94
12  2013-12-31    CHUBUT       PASO DE INDIOS   20.20  52.60
13  2014-12-31    CHUBUT       PASO DE INDIOS   19.92  54.19
14  2013-12-31    CHUBUT               RAWSON   20.30  55.67
15  2014-12-31    CHUBUT               RAWSON   19.78  61.22
16  2013-12-31    CHUBUT         RIO SENGUERR   20.25  55.86
17  2014-12-31    CHUBUT         RIO SENGUERR   20.10  59.01
18  2013-12-31    CHUBUT            SARMIENTO   20.73  49.13
19  2014-12-31    CHUBUT            SARMIENTO   19.92  48.21
20  2013-12-31    CHUBUT           TEHUELCHES   20.05  60.07
21  2014-12-31    CHUBUT           TEHUELCHES   19.41  61.21
22  2013-12-31    CHUBUT               TELSEN   20.01  51.90
23  2014-12-31    CHUBUT               TELSEN   19.79  54.01

In [8]:
datos_agrupado = datos.groupby("departamento").agg({
    "finura": ["mean", "std", "min", "max"],
    "rinde": ["mean", "std", "min", "max"],
})

In [9]:
datos_agrupado.stack()

                             finura      rinde
departamento
BIEDMA              mean  19.510000  56.930000
                    std    0.410122   2.729432
                    min   19.220000  55.000000
                    max   19.800000  58.860000
CUSHAMEN            mean  19.890000  60.410000
                    std    0.212132   4.157788
                    min   19.740000  57.470000
                    max   20.040000  63.350000
FLORENTINO AMEGHINO mean  19.415000  59.060000
                    std    0.162635   1.852620
                    min   19.300000  57.750000
                    max   19.530000  60.370000
FUTALEUFU           mean  20.935000  63.515000
                    std    0.940452   0.544472
                    min   20.270000  63.130000
                    max   21.600000  63.900000
GAIMAN              mean  20.595000  55.630000
                    std    0.289914   0.806102
                    min   20.390000  55.060000
                    max   20.800000  56.200000
LANGUIÑEO           mean  19.930000  58.170000
                    std    0.098995   3.917372
                    min   19.860000  55.400000
                    max   20.000000  60.940000
PASO DE INDIOS      mean  20.060000  53.395000
                    std    0.197990   1.124300
                    min   19.920000  52.600000
                    max   20.200000  54.190000
RAWSON              mean  20.040000  58.445000
                    std    0.367696   3.924443
                    min   19.780000  55.670000
                    max   20.300000  61.220000
RIO SENGUERR        mean  20.175000  57.435000
                    std    0.106066   2.227386
                    min   20.100000  55.860000
                    max   20.250000  59.010000
SARMIENTO           mean  20.325000  48.670000
                    std    0.572756   0.650538
                    min   19.920000  48.210000
                    max   20.730000  49.130000
TEHUELCHES          mean  19.730000  60.640000
                    std    0.452548   0.806102
                    min   19.410000  60.070000
                    max   20.050000  61.210000
TELSEN              mean  19.900000  52.955000
                    std    0.155563   1.491995
                    min   19.790000  51.900000
                    max   20.010000  54.010000

In [10]:
df_resultante = datos_agrupado.stack().reset_index()
df_resultante.rename(columns={'level_1':'metrica',}, inplace=True)
df_resultante

           departamento metrica     finura      rinde
0                BIEDMA    mean  19.510000  56.930000
1                BIEDMA     std   0.410122   2.729432
2                BIEDMA     min  19.220000  55.000000
3                BIEDMA     max  19.800000  58.860000
4              CUSHAMEN    mean  19.890000  60.410000
5              CUSHAMEN     std   0.212132   4.157788
6              CUSHAMEN     min  19.740000  57.470000
7              CUSHAMEN     max  20.040000  63.350000
8   FLORENTINO AMEGHINO    mean  19.415000  59.060000
9   FLORENTINO AMEGHINO     std   0.162635   1.852620
10  FLORENTINO AMEGHINO     min  19.300000  57.750000
11  FLORENTINO AMEGHINO     max  19.530000  60.370000
12            FUTALEUFU    mean  20.935000  63.515000
13            FUTALEUFU     std   0.940452   0.544472
14            FUTALEUFU     min  20.270000  63.130000
15            FUTALEUFU     max  21.600000  63.900000
16               GAIMAN    mean  20.595000  55.630000
17               GAIMAN     std   0.289914   0.806102
18               GAIMAN     min  20.390000  55.060000
19               GAIMAN     max  20.800000  56.200000
20            LANGUIÑEO    mean  19.930000  58.170000
21            LANGUIÑEO     std   0.098995   3.917372
22            LANGUIÑEO     min  19.860000  55.400000
23            LANGUIÑEO     max  20.000000  60.940000
24       PASO DE INDIOS    mean  20.060000  53.395000
25       PASO DE INDIOS     std   0.197990   1.124300
26       PASO DE INDIOS     min  19.920000  52.600000
27       PASO DE INDIOS     max  20.200000  54.190000
28               RAWSON    mean  20.040000  58.445000
29               RAWSON     std   0.367696   3.924443
30               RAWSON     min  19.780000  55.670000
31               RAWSON     max  20.300000  61.220000
32         RIO SENGUERR    mean  20.175000  57.435000
33         RIO SENGUERR     std   0.106066   2.227386
34         RIO SENGUERR     min  20.100000  55.860000
35         RIO SENGUERR     max  20.250000  59.010000
36            SARMIENTO    mean  20.325000  48.670000
37            SARMIENTO     std   0.572756   0.650538
38            SARMIENTO     min  19.920000  48.210000
39            SARMIENTO     max  20.730000  49.130000
40           TEHUELCHES    mean  19.730000  60.640000
41           TEHUELCHES     std   0.452548   0.806102
42           TEHUELCHES     min  19.410000  60.070000
43           TEHUELCHES     max  20.050000  61.210000
44               TELSEN    mean  19.900000  52.955000
45               TELSEN     std   0.155563   1.491995
46               TELSEN     min  19.790000  51.900000
47               TELSEN     max  20.010000  54.010000

Por último, guardamos el DataFrame como archivo CSV.

In [ ]:
df_resultante.to_csv("nuevo_porcentajes_f_r.csv", index=False)