# Combinar dataset con mirabueno

In [1]:
import pandas as pd

Este dataset representa los datos climaticos y de produccin de un campo de Chubut

In [9]:
datos_mirabueno = pd.read_csv('datos/datos_produccion_clima_mirabueno.csv', sep=",")
datos_mirabueno

,fecha,provincia,departamento,carneros,ovejas,borregos,capones,corderos,esquila,total_ovinos,...,porcentaje_paricion,temp_media,temp_min,tem_max,humedad,cant_lluvia,rad_solar,vel_viento,acumulado_anual,acumulado_verano
0,31/12/1985,CHUBUT,MIRABUENO,50,1419,563,690,912,3514,3634,...,64.27,14.3,6.4,20.9,57.6,208.6,4312.72,6.1,208.1,56.1
1,31/12/1986,CHUBUT,MIRABUENO,53,1520,605,1045,680,3783,3903,...,44.74,12.9,5.8,20.5,58.1,130.3,4236.36,6.8,130.0,20.7
2,31/12/1987,CHUBUT,MIRABUENO,67,1928,637,964,512,3988,4108,...,26.56,13.8,6.8,20.7,60.3,199.5,4142.41,6.4,199.3,77.1
3,31/12/1988,CHUBUT,MIRABUENO,55,1560,575,1210,310,3590,3710,...,19.87,12.9,5.5,20.4,54.9,85.5,4225.09,6.3,85.4,29.0
4,31/12/1989,CHUBUT,MIRABUENO,42,1210,457,1091,150,2830,2950,...,12.40,14.5,7.1,21.9,56.5,92.5,4195.38,6.3,92.0,12.8
5,31/12/1990,CHUBUT,MIRABUENO,35,998,390,969,124,2396,2516,...,12.42,14.2,6.8,21.7,56.2,96.0,4234.69,7.4,95.8,0.8
6,31/12/1991,CHUBUT,MIRABUENO,39,1122,407,995,60,2503,2623,...,5.35,13.2,5.8,20.6,60.3,240.0,4283.24,6.3,239.7,41.5
7,31/12/1992,CHUBUT,MIRABUENO,39,1125,451,1225,70,2790,2910,...,6.22,14.4,4.7,19.9,62.2,335.2,4278.28,6.4,334.8,109.7
8,31/12/1993,CHUBUT,MIRABUENO,43,1240,447,1090,65,2765,2885,...,5.24,14.8,5.5,21.0,58.1,155.7,4290.75,5.9,155.2,72.2
9,31/12/1994,CHUBUT,MIRABUENO,32,925,428,1342,34,2641,2761,...,3.68,13.5,4.6,24.3,53.7,82.5,4140.00,15.5,82.3,22.1
10,31/12/1995,CHUBUT,MIRABUENO,41,1159,361,239,527,2207,2327,...,45.47,11.9,2.6,22.0,18.5,267.8,4239.63,14.1,267.2,92.2
11,31/12/1996,CHUBUT,MIRABUENO,30,849,354,643,410,2166,2286,...,48.29,13.9,5.3,22.9,42.6,59.8,4197.63,5.8,59.6,17.8
12,31/12/1997,CHUBUT,MIRABUENO,27,768,319,426,520,1940,2060,...,67.71,13.0,6.4,20.0,56.3,278.6,4178.99,5.9,278.2,87.2
13,31/12/1998,CHUBUT,MIRABUENO,39,1124,453,802,507,2805,2925,...,45.11,13.5,6.7,20.7,49.9,355.0,4250.36,6.7,354.6,44.2
14,31/12/1999,CHUBUT,MIRABUENO,39,1124,484,966,507,3000,3120,...,45.11,12.4,5.6,19.3,55.1,302.4,4200.69,12.2,302.1,106.8
15,31/12/2000,CHUBUT,MIRABUENO,57,1632,515,444,672,3200,3320,...,41.18,14.0,5.5,23.0,42.0,212.5,4239.30,11.1,211.9,54.3
16,31/12/2001,CHUBUT,MIRABUENO,48,1378,544,1089,450,3389,3509,...,32.66,13.3,6.1,20.5,21.9,188.1,4201.26,6.5,187.7,38.8
17,31/12/2002,CHUBUT,MIRABUENO,59,1688,561,488,824,3500,3620,...,48.82,12.7,6.4,19.5,56.4,218.0,4259.19,9.0,217.7,31.3
18,31/12/2003,CHUBUT,MIRABUENO,68,1952,615,855,480,3850,3970,...,24.59,12.2,3.7,22.2,55.7,161.0,4894.20,8.2,160.7,38.0
19,31/12/2004,CHUBUT,MIRABUENO,65,1860,580,423,816,3624,3744,...,43.87,12.9,4.9,22.4,58.2,143.9,4916.00,7.9,143.4,36.6
20,31/12/2005,CHUBUT,MIRABUENO,108,3083,763,147,820,4239,4921,...,26.60,12.5,4.3,21.5,61.6,179.8,5019.00,7.9,179.5,56.4
21,31/12/2006,CHUBUT,MIRABUENO,65,1850,582,702,555,3634,3754,...,30.00,13.4,6.0,21.1,51.5,200.5,4392.70,8.8,200.0,19.8
22,31/12/2007,CHUBUT,MIRABUENO,64,1842,506,775,79,3146,3266,...,4.29,12.5,5.2,20.0,50.9,194.4,4384.80,7.4,194.0,100.5
23,31/12/2008,CHUBUT,MIRABUENO,43,1232,351,136,500,1677,2262,...,40.58,13.4,5.8,21.1,54.3,163.3,4129.40,6.8,162.5,48.1
24,31/12/2009,CHUBUT,MIRABUENO,39,1101,318,193,400,1931,2051,...,36.33,13.4,6.0,20.8,50.1,168.5,4093.60,9.4,168.1,27.3
25,31/12/2010,CHUBUT,MIRABUENO,35,1009,363,855,79,2221,2341,...,7.83,13.1,5.7,20.6,50.5,184.0,4439.20,8.4,183.7,81.8
26,31/12/2011,CHUBUT,MIRABUENO,34,970,275,192,300,1651,1771,...,30.93,13.8,6.3,21.3,50.6,130.7,4266.20,6.8,130.1,34.2
27,31/12/2012,CHUBUT,MIRABUENO,31,896,283,186,432,1708,1828,...,48.21,13.5,6.1,20.9,50.4,171.8,4208.40,4.9,171.5,99.1
28,31/12/2013,CHUBUT,MIRABUENO,32,923,325,234,582,1976,2096,...,63.06,13.6,6.8,20.7,56.3,197.6,4248.90,4.4,197.4,88.6
29,31/12/2014,CHUBUT,MIRABUENO,63,1800,451,394,200,2788,2908,...,11.11,13.6,6.7,20.6,54.0,187.2,4227.00,4.8,186.6,11.5
30,31/12/2015,CHUBUT,MIRABUENO,75,2130,654,159,1200,2738,4218,...,56.34,13.8,6.3,21.0,51.9,112.9,4342.40,6.5,112.6,25.3
31,31/12/2016,CHUBUT,MIRABUENO,81,2311,683,134,1200,3289,4409,...,51.93,13.5,6.4,20.8,61.4,218.0,4168.50,7.2,217.4,45.0
32,31/12/2017,CHUBUT,MIRABUENO,71,2032,701,264,1455,3484,4523,...,71.60,14.2,6.8,21.6,57.5,265.2,4218.70,6.4,264.8,51.4
33,31/12/2018,CHUBUT,MIRABUENO,42,1200,478,543,820,2963,3083,...,68.33,13.8,6.0,21.6,55.8,93.2,4166.80,4.1,92.7,19.1
34,31/12/2019,CHUBUT,MIRABUENO,103,2940,806,220,1129,3520,5198,...,38.40,13.6,5.8,21.4,55.8,170.7,4229.90,5.1,170.2,77.6
35,31/12/2020,CHUBUT,MIRABUENO,71,2021,533,385,430,3320,3440,...,21.28,14.3,6.6,22.0,54.5,92.0,4279.90,5.7,91.5,7.6

Se lo va combinar con cada uno de los datasets de clima y produccion de los departamentos de chubut

In [5]:
datos_chubut_1 = pd.read_csv('datos_producidos/merged_inner.csv', sep=",")
datos_chubut_2 = pd.read_csv('datos_producidos/merged_left_join.csv', sep=",")
datos_chubut_3 = pd.read_csv('datos_producidos/merged_full_join.csv', sep=",")
datos_chubut_1

,anio,provincia,departamento,carneros,ovejas,borregos,capones,corderos_corderas,total_ovinos,kg_lana,finura,rinde,PROMEDIO_HUMEDAD,TOTAL_LLUVIA,PROMEDIO_T_MAX,PROMEDIO_T_MED,PROMEDIO_T_MIN
0,2000-12-31,CHUBUT,RAWSON,2355,57320,20632,24405,18609,123321,258400.0,17.66,61.53,42.10,212.6,23.00,14.10,5.50
1,2001-12-31,CHUBUT,RAWSON,2226,54176,19500,23067,17588,116557,258400.0,18.15,60.74,21.90,188.1,20.60,13.40,6.10
2,2002-12-31,CHUBUT,RAWSON,1584,38558,13879,16417,12518,82956,256880.0,19.99,60.19,56.50,218.0,19.60,12.80,6.50
3,2003-12-31,CHUBUT,RAWSON,2252,54793,19722,23330,17789,117886,323760.0,20.90,59.90,55.80,161.0,22.30,12.30,3.80
4,2004-12-31,CHUBUT,RAWSON,2463,59959,21582,25529,19466,128999,332880.0,19.02,60.91,58.30,143.9,22.50,12.90,4.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,2020-12-31,CHUBUT,RAWSON,2273,74096,18058,19267,22102,135796,205200.0,19.57,61.66,54.50,92.0,22.10,14.40,6.70
161,2020-12-31,CHUBUT,RIO SENGUERR,15609,360905,146961,123560,112227,759262,2311200.0,20.28,57.70,61.65,298.8,16.75,9.85,3.50
162,2020-12-31,CHUBUT,SARMIENTO,3681,99173,27021,32939,20498,183312,851850.0,19.37,48.32,42.90,21.6,17.90,12.10,6.70
163,2020-12-31,CHUBUT,TEHUELCHES,8071,197382,87268,86893,54493,434107,1903500.0,20.02,61.85,39.80,414.0,11.85,6.60,1.60
164,2020-12-31,CHUBUT,TELSEN,2870,79157,25804,36901,18984,163716,614250.0,21.55,52.96,46.63,304.4,16.60,10.60,4.63

Para poder hacer la combinacion sera necesario a los datasets quitarles columnas, renombrarlas pra que la informacion del mirabueno coincida con la que pudimos conseguir para los departamentos.

Cambios en datos de mirabueno:
1. Se agregaron manualmente la columna provincia, departamento y total de ovinos. Vamos a considerar al campo "El mirabueno" como un departamento para tener mas datos.
2. Se elimaron columnas ya que no tenemos esa información para los departamentos.
3. Se renombraron las columnas
4. Se transformo el campo fecha en un datetime

In [11]:
datos_mirabueno = datos_mirabueno.drop(
    columns=['esquila', 'kilo_lana_p/animal', 'porcentaje_paricion', 'rad_solar', 'acumulado_anual', 'acumulado_verano', 'vel_viento'])
datos_mirabueno['fecha'] = pd.to_datetime(datos_mirabueno['fecha'])
datos_mirabueno.columns = ['fecha', 'provincia', 'departamento', 'carneros', 'ovejas', 
                           'borregos', 'capones', 'cordero/as', 'total_ovinos',
                           'kilos_lana', 'rinde', 'finura', 'temp_media', 'temp_min',
                           'tem_max', 'humedad', 'cant_lluvia']
datos_mirabueno

,fecha,provincia,departamento,carneros,ovejas,borregos,capones,cordero/as,total_ovinos,kilos_lana,rinde,finura,temp_media,temp_min,tem_max,humedad,cant_lluvia
0,1985-12-31,CHUBUT,MIRABUENO,50,1419,563,690,912,3634,15600,60.46,19.26,14.3,6.4,20.9,57.6,208.6
1,1986-12-31,CHUBUT,MIRABUENO,53,1520,605,1045,680,3903,18167,61.52,19.86,12.9,5.8,20.5,58.1,130.3
2,1987-12-31,CHUBUT,MIRABUENO,67,1928,637,964,512,4108,11200,55.77,19.41,13.8,6.8,20.7,60.3,199.5
3,1988-12-31,CHUBUT,MIRABUENO,55,1560,575,1210,310,3710,13197,61.69,18.65,12.9,5.5,20.4,54.9,85.5
4,1989-12-31,CHUBUT,MIRABUENO,42,1210,457,1091,150,2950,12300,57.13,19.82,14.5,7.1,21.9,56.5,92.5
5,1990-12-31,CHUBUT,MIRABUENO,35,998,390,969,124,2516,13900,59.84,20.23,14.2,6.8,21.7,56.2,96.0
6,1991-12-31,CHUBUT,MIRABUENO,39,1122,407,995,60,2623,15800,60.56,20.47,13.2,5.8,20.6,60.3,240.0
7,1992-12-31,CHUBUT,MIRABUENO,39,1125,451,1225,70,2910,11600,54.04,19.80,14.4,4.7,19.9,62.2,335.2
8,1993-12-31,CHUBUT,MIRABUENO,43,1240,447,1090,65,2885,10306,58.81,19.30,14.8,5.5,21.0,58.1,155.7
9,1994-12-31,CHUBUT,MIRABUENO,32,925,428,1342,34,2761,9000,61.83,18.87,13.5,4.6,24.3,53.7,82.5
10,1995-12-31,CHUBUT,MIRABUENO,41,1159,361,239,527,2327,9931,64.37,18.61,11.9,2.6,22.0,18.5,267.8
11,1996-12-31,CHUBUT,MIRABUENO,30,849,354,643,410,2286,9730,60.43,18.51,13.9,5.3,22.9,42.6,59.8
12,1997-12-31,CHUBUT,MIRABUENO,27,768,319,426,520,2060,11763,56.21,19.66,13.0,6.4,20.0,56.3,278.6
13,1998-12-31,CHUBUT,MIRABUENO,39,1124,453,802,507,2925,12400,61.39,19.09,13.5,6.7,20.7,49.9,355.0
14,1999-12-31,CHUBUT,MIRABUENO,39,1124,484,966,507,3120,13700,53.18,19.54,12.4,5.6,19.3,55.1,302.4
15,2000-12-31,CHUBUT,MIRABUENO,57,1632,515,444,672,3320,17349,65.27,20.80,14.0,5.5,23.0,42.0,212.5
16,2001-12-31,CHUBUT,MIRABUENO,48,1378,544,1089,450,3509,13522,61.80,21.00,13.3,6.1,20.5,21.9,188.1
17,2002-12-31,CHUBUT,MIRABUENO,59,1688,561,488,824,3620,17358,61.65,20.93,12.7,6.4,19.5,56.4,218.0
18,2003-12-31,CHUBUT,MIRABUENO,68,1952,615,855,480,3970,11554,61.10,19.60,12.2,3.7,22.2,55.7,161.0
19,2004-12-31,CHUBUT,MIRABUENO,65,1860,580,423,816,3744,11267,57.50,19.20,12.9,4.9,22.4,58.2,143.9
20,2005-12-31,CHUBUT,MIRABUENO,108,3083,763,147,820,4921,15753,56.80,18.50,12.5,4.3,21.5,61.6,179.8
21,2006-12-31,CHUBUT,MIRABUENO,65,1850,582,702,555,3754,13785,57.80,19.30,13.4,6.0,21.1,51.5,200.5
22,2007-12-31,CHUBUT,MIRABUENO,64,1842,506,775,79,3266,10336,58.30,19.30,12.5,5.2,20.0,50.9,194.4
23,2008-12-31,CHUBUT,MIRABUENO,43,1232,351,136,500,2262,5245,58.90,20.36,13.4,5.8,21.1,54.3,163.3
24,2009-12-31,CHUBUT,MIRABUENO,39,1101,318,193,400,2051,8739,53.10,19.60,13.4,6.0,20.8,50.1,168.5
25,2010-12-31,CHUBUT,MIRABUENO,35,1009,363,855,79,2341,9164,56.70,18.78,13.1,5.7,20.6,50.5,184.0
26,2011-12-31,CHUBUT,MIRABUENO,34,970,275,192,300,1771,6516,55.00,18.50,13.8,6.3,21.3,50.6,130.7
27,2012-12-31,CHUBUT,MIRABUENO,31,896,283,186,432,1828,8376,53.90,20.20,13.5,6.1,20.9,50.4,171.8
28,2013-12-31,CHUBUT,MIRABUENO,32,923,325,234,582,2096,9892,53.90,20.30,13.6,6.8,20.7,56.3,197.6
29,2014-12-31,CHUBUT,MIRABUENO,63,1800,451,394,200,2908,10510,56.10,19.40,13.6,6.7,20.6,54.0,187.2
30,2015-12-31,CHUBUT,MIRABUENO,75,2130,654,159,1200,4218,10776,59.10,19.30,13.8,6.3,21.0,51.9,112.9
31,2016-12-31,CHUBUT,MIRABUENO,81,2311,683,134,1200,4409,10990,60.00,19.80,13.5,6.4,20.8,61.4,218.0
32,2017-12-31,CHUBUT,MIRABUENO,71,2032,701,264,1455,4523,11200,59.30,19.50,14.2,6.8,21.6,57.5,265.2
33,2018-12-31,CHUBUT,MIRABUENO,42,1200,478,543,820,3083,9193,61.30,19.80,13.8,6.0,21.6,55.8,93.2
34,2019-12-31,CHUBUT,MIRABUENO,103,2940,806,220,1129,5198,13027,56.90,19.80,13.6,5.8,21.4,55.8,170.7
35,2020-12-31,CHUBUT,MIRABUENO,71,2021,533,385,430,3440,12136,56.10,19.60,14.3,6.6,22.0,54.5,92.0

Cambios en datos de produccion:
1. Se cambio la fecha 01-01 por 31-12 manualmente. Ya que tiene mucho sentido, es una manera de decir estos son los datos que se juntaron en el año.
2. Se renombraron las columnas

In [12]:
datos_chubut_1.columns = ['fecha', 'provincia', 'departamento', 'carneros', 'ovejas', 'borregos',
                          'capones', 'cordero/as', 'total_ovinos', 'kilos_lana', 'finura',
                          'rinde', 'humedad', 'cant_lluvia', 'tem_max','temp_media', 'temp_min']

datos_chubut_2.columns = ['fecha', 'provincia', 'departamento', 'carneros', 'ovejas', 'borregos',
                          'capones', 'cordero/as', 'total_ovinos', 'kilos_lana', 'finura',
                          'rinde', 'humedad', 'cant_lluvia', 'tem_max','temp_media', 'temp_min']

datos_chubut_3.columns = ['fecha', 'provincia', 'departamento', 'carneros', 'ovejas', 'borregos',
                          'capones', 'cordero/as', 'total_ovinos', 'kilos_lana', 'finura',
                          'rinde', 'humedad', 'cant_lluvia', 'tem_max','temp_media', 'temp_min']

datos_chubut_1

,fecha,provincia,departamento,carneros,ovejas,borregos,capones,cordero/as,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
0,2000-12-31,CHUBUT,RAWSON,2355,57320,20632,24405,18609,123321,258400.0,17.66,61.53,42.10,212.6,23.00,14.10,5.50
1,2001-12-31,CHUBUT,RAWSON,2226,54176,19500,23067,17588,116557,258400.0,18.15,60.74,21.90,188.1,20.60,13.40,6.10
2,2002-12-31,CHUBUT,RAWSON,1584,38558,13879,16417,12518,82956,256880.0,19.99,60.19,56.50,218.0,19.60,12.80,6.50
3,2003-12-31,CHUBUT,RAWSON,2252,54793,19722,23330,17789,117886,323760.0,20.90,59.90,55.80,161.0,22.30,12.30,3.80
4,2004-12-31,CHUBUT,RAWSON,2463,59959,21582,25529,19466,128999,332880.0,19.02,60.91,58.30,143.9,22.50,12.90,4.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,2020-12-31,CHUBUT,RAWSON,2273,74096,18058,19267,22102,135796,205200.0,19.57,61.66,54.50,92.0,22.10,14.40,6.70
161,2020-12-31,CHUBUT,RIO SENGUERR,15609,360905,146961,123560,112227,759262,2311200.0,20.28,57.70,61.65,298.8,16.75,9.85,3.50
162,2020-12-31,CHUBUT,SARMIENTO,3681,99173,27021,32939,20498,183312,851850.0,19.37,48.32,42.90,21.6,17.90,12.10,6.70
163,2020-12-31,CHUBUT,TEHUELCHES,8071,197382,87268,86893,54493,434107,1903500.0,20.02,61.85,39.80,414.0,11.85,6.60,1.60
164,2020-12-31,CHUBUT,TELSEN,2870,79157,25804,36901,18984,163716,614250.0,21.55,52.96,46.63,304.4,16.60,10.60,4.63

Ahora se va a concatenar los datos del mirabueno a los otros tres dataset

In [13]:
datos_1 = pd.concat([datos_chubut_1, datos_mirabueno])
datos_1['fecha'] = pd.to_datetime(datos_1['fecha'])
datos_1 = datos_1.sort_values(['departamento', 'fecha'])
datos_1

,fecha,provincia,departamento,carneros,ovejas,borregos,capones,cordero/as,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
60,2012-12-31,CHUBUT,BIEDMA,5785,93378,30168,48447,16071,193849,649130.0,19.80,58.06,58.40,46.4,18.10,12.40,6.70
72,2013-12-31,CHUBUT,BIEDMA,5376,82998,25341,47350,26832,187897,620176.0,19.60,56.68,64.70,226.5,19.90,14.20,8.80
84,2014-12-31,CHUBUT,BIEDMA,4785,82706,29379,35155,29900,181925,649130.0,20.10,61.19,60.50,331.3,20.60,14.70,9.20
95,2015-12-31,CHUBUT,BIEDMA,4440,89262,29663,35437,32343,191145,672480.0,18.58,58.18,58.70,114.2,22.20,15.80,10.20
106,2016-12-31,CHUBUT,BIEDMA,4452,82295,33662,33470,21326,175205,653800.0,17.99,59.93,57.50,88.9,25.20,18.60,12.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,2016-12-31,CHUBUT,TELSEN,4896,80262,26471,39243,20290,171162,637000.0,20.20,53.55,50.80,820.0,17.47,11.57,5.77
129,2017-12-31,CHUBUT,TELSEN,4640,77556,27296,36570,17750,163812,637000.0,19.11,56.01,47.17,660.1,16.60,10.93,5.03
140,2018-12-31,CHUBUT,TELSEN,4832,79117,28366,37558,21933,171806,637000.0,20.38,54.64,47.93,604.2,17.63,11.33,5.03
152,2019-12-31,CHUBUT,TELSEN,4781,80109,28428,38109,17731,169158,613021.5,16.88,53.83,47.57,358.4,17.53,11.17,4.83
164,2020-12-31,CHUBUT,TELSEN,2870,79157,25804,36901,18984,163716,614250.0,21.55,52.96,46.63,304.4,16.60,10.60,4.63

In [14]:
datos_1.to_csv('datos_producidos/datos_1.csv', index=False)

In [15]:
datos_2 = pd.concat([datos_chubut_2, datos_mirabueno])
datos_2['fecha'] = pd.to_datetime(datos_2['fecha'])
datos_2 = datos_2.sort_values(['departamento', 'fecha'])
datos_2

,fecha,provincia,departamento,carneros,ovejas,borregos,capones,cordero/as,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
0,2000-12-31,CHUBUT,BIEDMA,4627,88905,31529,41328,22410,188799,793900.0,20.39,59.21,NaN,NaN,NaN,NaN,NaN
16,2001-12-31,CHUBUT,BIEDMA,4933,94817,33626,44076,23900,201352,793900.0,19.01,59.03,NaN,NaN,NaN,NaN,NaN
32,2002-12-31,CHUBUT,BIEDMA,4506,86622,30720,40267,21835,183950,789230.0,20.53,57.17,NaN,NaN,NaN,NaN,NaN
48,2003-12-31,CHUBUT,BIEDMA,5148,98950,35092,45997,24942,210129,994710.0,20.57,58.14,NaN,NaN,NaN,NaN,NaN
64,2004-12-31,CHUBUT,BIEDMA,4764,91580,32478,42571,23085,194478,1022730.0,20.68,57.63,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,2016-12-31,CHUBUT,TOTAL,130635,1947672,658063,703023,554340,3993733,14000000.0,20.20,57.48,NaN,NaN,NaN,NaN,NaN
287,2017-12-31,CHUBUT,TOTAL,124046,1917298,652423,672122,606862,3972751,14000000.0,21.39,58.88,NaN,NaN,NaN,NaN,NaN
303,2018-12-31,CHUBUT,TOTAL,120807,1929004,643675,656187,595247,3944920,14000000.0,19.78,58.82,NaN,NaN,NaN,NaN,NaN
319,2019-12-31,CHUBUT,TOTAL,127625,1996422,681206,673858,597226,4076337,13473000.0,19.16,56.04,NaN,NaN,NaN,NaN,NaN
335,2020-12-31,CHUBUT,TOTAL,79860,1992008,669777,666432,576856,3984933,13500000.0,20.36,56.57,NaN,NaN,NaN,NaN,NaN

In [16]:
datos_2.to_csv('datos_producidos/datos_2.csv', index=False)

In [17]:
datos_3 = pd.concat([datos_chubut_3, datos_mirabueno])
datos_3['fecha'] = pd.to_datetime(datos_3['fecha'])
datos_3 = datos_3.sort_values(['departamento', 'fecha'])
datos_3

,fecha,provincia,departamento,carneros,ovejas,borregos,capones,cordero/as,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
0,2000-12-31,CHUBUT,BIEDMA,4627.0,88905.0,31529.0,41328.0,22410.0,188799.0,793900.0,20.39,59.21,NaN,NaN,NaN,NaN,NaN
16,2001-12-31,CHUBUT,BIEDMA,4933.0,94817.0,33626.0,44076.0,23900.0,201352.0,793900.0,19.01,59.03,NaN,NaN,NaN,NaN,NaN
32,2002-12-31,CHUBUT,BIEDMA,4506.0,86622.0,30720.0,40267.0,21835.0,183950.0,789230.0,20.53,57.17,NaN,NaN,NaN,NaN,NaN
48,2003-12-31,CHUBUT,BIEDMA,5148.0,98950.0,35092.0,45997.0,24942.0,210129.0,994710.0,20.57,58.14,NaN,NaN,NaN,NaN,NaN
64,2004-12-31,CHUBUT,BIEDMA,4764.0,91580.0,32478.0,42571.0,23085.0,194478.0,1022730.0,20.68,57.63,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,2016-12-31,CHUBUT,TOTAL,130635.0,1947672.0,658063.0,703023.0,554340.0,3993733.0,14000000.0,20.20,57.48,NaN,NaN,NaN,NaN,NaN
287,2017-12-31,CHUBUT,TOTAL,124046.0,1917298.0,652423.0,672122.0,606862.0,3972751.0,14000000.0,21.39,58.88,NaN,NaN,NaN,NaN,NaN
303,2018-12-31,CHUBUT,TOTAL,120807.0,1929004.0,643675.0,656187.0,595247.0,3944920.0,14000000.0,19.78,58.82,NaN,NaN,NaN,NaN,NaN
319,2019-12-31,CHUBUT,TOTAL,127625.0,1996422.0,681206.0,673858.0,597226.0,4076337.0,13473000.0,19.16,56.04,NaN,NaN,NaN,NaN,NaN
335,2020-12-31,CHUBUT,TOTAL,79860.0,1992008.0,669777.0,666432.0,576856.0,3984933.0,13500000.0,20.36,56.57,NaN,NaN,NaN,NaN,NaN

In [18]:
datos_3.to_csv('datos_producidos/datos_3.csv', index=False)

Se saco el .0 de las columnas enteras, se eliminaron las filas TOTAL