# 1.10. Aplicar métricas de existencias

In [12]:
import numpy as np
import pandas as pd
import random

Después de generar el nuevo archivo con las nuevas métricas para generar los valores, cargamos este archivo csv para convertirlo en un DataFrame y trabajarlo en combinación con el otro más adelante.

In [13]:
metricas = pd.read_csv("nuevo_porcentajes_existencias.csv")
metricas

,departamento,metrica,carneros,ovejas,borregos,capones,corderos_corderas
0,BIEDMA,mean,2.155000,39.825000,17.205000,19.060000,21.750000
1,BIEDMA,std,0.176777,1.732412,1.972828,0.466690,0.395980
2,BIEDMA,min,2.030000,38.600000,15.810000,18.730000,21.470000
3,BIEDMA,max,2.280000,41.050000,18.600000,19.390000,22.030000
4,CUSHAMEN,mean,2.560000,46.715000,15.110000,10.480000,25.135000
5,CUSHAMEN,std,0.197990,2.991062,0.268701,0.664680,2.241528
6,CUSHAMEN,min,2.420000,44.600000,14.920000,10.010000,23.550000
7,CUSHAMEN,max,2.700000,48.830000,15.300000,10.950000,26.720000
8,FLORENTINO AMEGHINO,mean,2.470000,39.950000,17.490000,14.715000,25.370000
9,FLORENTINO AMEGHINO,std,0.127279,0.919239,1.810193,0.148492,0.608112
10,FLORENTINO AMEGHINO,min,2.380000,39.300000,16.210000,14.610000,24.940000
11,FLORENTINO AMEGHINO,max,2.560000,40.600000,18.770000,14.820000,25.800000
12,FUTALEUFU,mean,3.170000,48.380000,12.650000,11.805000,23.985000
13,FUTALEUFU,std,0.042426,1.979899,0.070711,1.378858,3.471894
14,FUTALEUFU,min,3.140000,46.980000,12.600000,10.830000,21.530000
15,FUTALEUFU,max,3.200000,49.780000,12.700000,12.780000,26.440000
16,GAIMAN,mean,2.450000,48.435000,12.900000,14.045000,22.170000
17,GAIMAN,std,0.028284,4.772971,1.414214,1.195010,4.525483
18,GAIMAN,min,2.430000,45.060000,11.900000,13.200000,18.970000
19,GAIMAN,max,2.470000,51.810000,13.900000,14.890000,25.370000
20,LANGUIÑEO,mean,2.900000,39.845000,18.255000,18.065000,20.935000
21,LANGUIÑEO,std,0.169706,0.289914,0.954594,0.629325,0.784889
22,LANGUIÑEO,min,2.780000,39.640000,17.580000,17.620000,20.380000
23,LANGUIÑEO,max,3.020000,40.050000,18.930000,18.510000,21.490000
24,PASO DE INDIOS,mean,2.585000,45.245000,14.645000,17.865000,19.660000
25,PASO DE INDIOS,std,0.021213,2.679935,0.275772,0.106066,2.291026
26,PASO DE INDIOS,min,2.570000,43.350000,14.450000,17.790000,18.040000
27,PASO DE INDIOS,max,2.600000,47.140000,14.840000,17.940000,21.280000
28,RAWSON,mean,2.835000,43.610000,14.665000,17.150000,21.740000
29,RAWSON,std,0.049497,1.654630,0.332340,0.042426,2.078894
30,RAWSON,min,2.800000,42.440000,14.430000,17.120000,20.270000
31,RAWSON,max,2.870000,44.780000,14.900000,17.180000,23.210000
32,RIO SENGUERR,mean,2.650000,43.440000,17.120000,14.450000,22.335000
33,RIO SENGUERR,std,0.183848,0.862670,1.329361,0.608112,0.318198
34,RIO SENGUERR,min,2.520000,42.830000,16.180000,14.020000,22.110000
35,RIO SENGUERR,max,2.780000,44.050000,18.060000,14.880000,22.560000
36,SARMIENTO,mean,3.095000,45.570000,14.815000,17.220000,19.300000
37,SARMIENTO,std,0.289914,2.305168,0.459619,0.466690,1.668772
38,SARMIENTO,min,2.890000,43.940000,14.490000,16.890000,18.120000
39,SARMIENTO,max,3.300000,47.200000,15.140000,17.550000,20.480000
40,TEHUELCHES,mean,3.070000,39.755000,17.280000,19.750000,20.135000
41,TEHUELCHES,std,0.070711,0.289914,0.339411,0.947523,0.968736
42,TEHUELCHES,min,3.020000,39.550000,17.040000,19.080000,19.450000
43,TEHUELCHES,max,3.120000,39.960000,17.520000,20.420000,20.820000
44,TELSEN,mean,2.625000,43.115000,16.570000,18.905000,18.785000
45,TELSEN,std,0.134350,0.615183,0.028284,3.740595,4.518412
46,TELSEN,min,2.530000,42.680000,16.550000,16.260000,15.590000
47,TELSEN,max,2.720000,43.550000,16.590000,21.550000,21.980000

Lo siguiente es cargar el nuevo Dataset de datos productivos y el clima ajustados con los nuevos valores obtenidos de las estadísticas ganaderas de Chubut, y con una nueva columna de estado para saber cuáles son las filas que deben ser modificadas.

In [14]:
datos = pd.read_csv("actualizando_dataset - Existencias.csv")
datos

,fecha,provincia,estado,departamento,carneros,ovejas,borregos,capones,corderos_corderas,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
0,2012-12-31,CHUBUT,MODIFICABLE,BIEDMA,5785,93378,30168,48447,16071,132385,478116.0,19.80,58.06,58.40,46.40,18.10,12.40,6.70
1,2013-12-31,CHUBUT,REAL,BIEDMA,3925,70677,27227,33389,36961,172179,544941.0,19.80,55.00,64.70,226.50,19.90,14.20,8.80
2,2014-12-31,CHUBUT,REAL,BIEDMA,3223,61195,29491,29688,34926,158523,513951.0,19.22,58.86,60.50,331.30,20.60,14.70,9.20
3,2015-12-31,CHUBUT,MODIFICABLE,BIEDMA,4440,89262,29663,35437,32343,171145,672480.0,18.58,58.18,58.70,114.20,22.20,15.80,10.20
4,2016-12-31,CHUBUT,MODIFICABLE,BIEDMA,4452,82295,33662,33470,21326,175205,653800.0,17.99,59.93,57.50,88.90,25.20,18.60,12.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,2016-12-31,CHUBUT,MODIFICABLE,TELSEN,4896,80262,26471,39243,20290,171162,637000.0,20.20,53.55,50.80,273.33,17.47,11.57,5.77
160,2017-12-31,CHUBUT,MODIFICABLE,TELSEN,4640,77556,27296,36570,17750,163812,637000.0,19.11,56.01,47.17,220.03,16.60,10.93,5.03
161,2018-12-31,CHUBUT,MODIFICABLE,TELSEN,4832,79117,28366,37558,21933,171806,637000.0,20.38,54.64,47.93,201.40,17.63,11.33,5.03
162,2019-12-31,CHUBUT,MODIFICABLE,TELSEN,4781,80109,28428,38109,17731,169158,613021.5,16.88,53.83,47.57,119.47,17.53,11.17,4.83
163,2020-12-31,CHUBUT,MODIFICABLE,TELSEN,2870,79157,25804,36901,18984,163716,614250.0,21.55,52.96,46.63,101.47,16.60,10.60,4.63

Ahora vamos a separar este DataFrame en las filas que son modificables y las que no, obteniendo como resultado un DataFrame de datos modificables y un DataFrame de datos reales, que no tienen que ser modificados.

In [15]:
df_real = datos[datos['estado'] == 'REAL']
df_real

,fecha,provincia,estado,departamento,carneros,ovejas,borregos,capones,corderos_corderas,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
1,2013-12-31,CHUBUT,REAL,BIEDMA,3925,70677,27227,33389,36961,172179,544941.0,19.80,55.00,64.70,226.50,19.90,14.20,8.80
2,2014-12-31,CHUBUT,REAL,BIEDMA,3223,61195,29491,29688,34926,158523,513951.0,19.22,58.86,60.50,331.30,20.60,14.70,9.20
16,2013-12-31,CHUBUT,REAL,CUSHAMEN,4751,85946,26255,17619,41451,176022,479996.0,20.04,57.47,58.22,769.59,18.90,11.88,5.49
17,2014-12-31,CHUBUT,REAL,CUSHAMEN,4198,77263,26512,18975,46290,173238,578184.0,19.74,63.35,59.10,640.40,17.03,10.46,4.62
28,2013-12-31,CHUBUT,REAL,FLORENTINO AMEGHINO,9114,150199,71752,55841,95320,382226,1088145.0,19.30,57.75,55.10,135.50,18.30,11.80,5.20
29,2014-12-31,CHUBUT,REAL,FLORENTINO AMEGHINO,8893,140928,56282,51459,89550,347112,948220.0,19.53,60.37,52.90,174.10,16.90,10.70,4.30
43,2013-12-31,CHUBUT,REAL,FUTALEUFU,3594,55861,14255,14340,24160,112210,352880.0,21.60,63.90,69.95,653.46,16.79,10.09,3.60
44,2014-12-31,CHUBUT,REAL,FUTALEUFU,3436,51384,13783,11841,28919,109363,360959.0,21.55,62.93,69.60,614.79,15.13,9.04,3.30
58,2013-12-31,CHUBUT,REAL,GAIMAN,4102,87337,20059,25098,31970,168566,575499.0,20.80,56.20,56.33,149.50,20.70,13.27,6.13
59,2014-12-31,CHUBUT,REAL,GAIMAN,4936,90039,27772,26376,50701,199824,637321.0,20.39,55.06,57.60,137.93,20.47,13.07,5.83
67,2013-12-31,CHUBUT,REAL,LANGUIÑEO,7275,96402,45552,42406,49046,240681,798566.0,20.00,55.40,53.35,103.70,22.15,13.55,4.90
68,2015-12-31,CHUBUT,REAL,LANGUIÑEO,6151,87640,38874,40929,47517,221111,782652.0,19.86,60.94,48.10,13.50,21.80,13.00,3.40
79,2013-12-31,CHUBUT,REAL,PASO DE INDIOS,4653,85441,26190,32246,32703,181233,638623.0,20.20,52.60,47.80,89.40,21.10,13.80,6.10
80,2014-12-31,CHUBUT,REAL,PASO DE INDIOS,5398,89998,30804,37250,44180,207630,708994.0,19.92,54.19,45.70,117.10,21.60,14.40,7.20
100,2013-12-31,CHUBUT,REAL,RAWSON,1673,26143,8701,10029,11832,58378,202228.0,20.30,55.67,56.30,197.60,20.70,13.70,6.90
101,2014-12-31,CHUBUT,REAL,RAWSON,1446,21913,7450,8839,11982,51630,166901.0,19.78,61.22,54.00,187.20,20.60,13.70,6.80
116,2013-12-31,CHUBUT,REAL,RIO SENGUERR,17403,295275,124490,96655,155537,689360,2240084.0,20.25,55.86,59.35,105.77,15.93,10.03,4.60
117,2014-12-31,CHUBUT,REAL,RIO SENGUERR,15571,246882,90683,83406,123913,560455,1884950.0,20.10,59.01,62.25,127.03,15.57,9.33,3.63
131,2013-12-31,CHUBUT,REAL,SARMIENTO,5978,85638,26288,30644,32877,181425,663376.0,20.73,49.13,51.20,88.90,20.15,13.60,7.50
132,2014-12-31,CHUBUT,REAL,SARMIENTO,5269,80123,27608,32012,37346,182358,694471.0,19.92,48.21,48.90,69.45,20.35,13.95,8.15
144,2013-12-31,CHUBUT,REAL,TEHUELCHES,13577,177588,78690,85677,93487,449019,1630632.0,20.05,60.07,52.20,256.60,15.00,8.85,2.90
145,2014-12-31,CHUBUT,REAL,TEHUELCHES,13819,176838,75419,90371,86049,442496,1552294.0,19.41,61.21,71.35,150.53,12.53,6.73,1.53
156,2013-12-31,CHUBUT,REAL,TELSEN,3899,62509,23816,30940,22378,143542,501945.0,20.01,51.90,50.20,222.05,18.95,12.18,5.58
157,2014-12-31,CHUBUT,REAL,TELSEN,3495,59018,22886,22489,30400,138288,500937.0,19.79,54.01,46.18,270.02,20.82,13.58,6.22

In [16]:
df_modificable = datos[datos['estado'] == 'MODIFICABLE']
df_modificable

,fecha,provincia,estado,departamento,carneros,ovejas,borregos,capones,corderos_corderas,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
0,2012-12-31,CHUBUT,MODIFICABLE,BIEDMA,5785,93378,30168,48447,16071,132385,478116.0,19.80,58.06,58.40,46.40,18.10,12.40,6.70
3,2015-12-31,CHUBUT,MODIFICABLE,BIEDMA,4440,89262,29663,35437,32343,171145,672480.0,18.58,58.18,58.70,114.20,22.20,15.80,10.20
4,2016-12-31,CHUBUT,MODIFICABLE,BIEDMA,4452,82295,33662,33470,21326,175205,653800.0,17.99,59.93,57.50,88.90,25.20,18.60,12.90
5,2017-12-31,CHUBUT,MODIFICABLE,BIEDMA,4688,87179,33148,33947,20900,179862,653800.0,19.73,58.95,55.80,291.90,19.10,13.60,8.40
6,2018-12-31,CHUBUT,MODIFICABLE,BIEDMA,4767,86473,36233,31347,22289,181109,653800.0,18.86,58.89,56.30,99.00,21.00,14.80,9.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,2016-12-31,CHUBUT,MODIFICABLE,TELSEN,4896,80262,26471,39243,20290,171162,637000.0,20.20,53.55,50.80,273.33,17.47,11.57,5.77
160,2017-12-31,CHUBUT,MODIFICABLE,TELSEN,4640,77556,27296,36570,17750,163812,637000.0,19.11,56.01,47.17,220.03,16.60,10.93,5.03
161,2018-12-31,CHUBUT,MODIFICABLE,TELSEN,4832,79117,28366,37558,21933,171806,637000.0,20.38,54.64,47.93,201.40,17.63,11.33,5.03
162,2019-12-31,CHUBUT,MODIFICABLE,TELSEN,4781,80109,28428,38109,17731,169158,613021.5,16.88,53.83,47.57,119.47,17.53,11.17,4.83
163,2020-12-31,CHUBUT,MODIFICABLE,TELSEN,2870,79157,25804,36901,18984,163716,614250.0,21.55,52.96,46.63,101.47,16.60,10.60,4.63

Creamos una lista con los nombres de las categorías de ovinos

In [17]:
categorias_ovinos = ['carneros', 'ovejas', 'borregos', 'capones', 'corderos_corderas']

Después creamos una función llamada "aleatorio_rango", que toma como entrada una media, una desviación estándar, un valor mínimo y un valor máximo. La función utiliza la función "random.normalvariate" de Python para generar un valor aleatorio con la media y la desviación estándar dadas, y redondea el resultado a dos decimales. Si el valor generado está fuera del rango mínimo y máximo especificado, o si la suma acumulada de los valores generados excede el total de ovinos, la función vuelve a generar otro valor. Esto nos permite ajustar los valores aleatorios generados para que la suma total de los mismos sea exactamente igual al número total de ovinos.

In [ ]:
def aleatorio_rango(media, desvio, minimo, maximo, total_ovino, sum_calculado):
    maximo_sum = total_ovino - sum_calculado # El máximo permitido para esta categoría depende de la suma de las categorías anteriores
    valor_aleatorio = round(random.normalvariate(media, desvio), 2)
    while valor_aleatorio < minimo or valor_aleatorio > maximo or sum_calculado + valor_aleatorio > total_ovino:
        valor_aleatorio = round(random.normalvariate(media, desvio), 2)
    return valor_aleatorio

El siguiente paso consiste en recorrer el DataFrame modificable de manera iterativa, extrayendo los departamentos uno por uno y comparándolos con los departamentos presentes en el DataFrame de métricas. A continuación, se recorren las diferentes categorías correspondientes a los ovinos y se obtienen las métricas asociadas, tales como la media, el desvío, el mínimo y el máximo. Luego, se genera un valor aleatorio para cada categoría y se aplica la fórmula correspondiente para obtener el valor calculado. Finalmente, se almacena el valor obtenido en el DataFrame modificable.

In [ ]:
for index, row in df_modificable.iterrows():
    departamento = row['departamento']
    df1_departamento = metricas[metricas['departamento'] == departamento]
    total_ovino = row['total_ovinos']
    sum_calculado = 0
    
    # Generamos los valores aleatorios para cada categoría de ovinos
    valores = []
    for categoria in categorias_ovinos:
        media = df1_departamento[categoria].iloc[0]
        desvio = df1_departamento[categoria].iloc[1]
        minimo = df1_departamento[categoria].iloc[2]
        maximo = df1_departamento[categoria].iloc[3]
        valor_aleatorio = aleatorio_rango(media, desvio, minimo, maximo, total_ovino, sum_calculado)
        sum_calculado += valor_aleatorio
        valores.append(valor_aleatorio)
    
    # Ajustamos los valores calculados para que la suma sea igual a total_ovino
    factor_ajuste = total_ovino / sum(valores)
    valores_ajustados = [round(valor * factor_ajuste) for valor in valores]
    
    # Ajustamos la última categoría para que la suma total sea exactamente igual al total de ovinos
    diferencia = total_ovino - sum(valores_ajustados)
    valores_ajustados[-1] += diferencia
    
    # Almacenamos los valores calculados en las nuevas columnas del segundo DataFrame
    for i, categoria in enumerate(categorias_ovinos):
        df_modificable.loc[index, categoria] = valores_ajustados[i]

Como resultado obtenemos un nuevo DataFrame con los nuevos valores para cada categoría ovina en base al total de ovinos.

In [30]:
df_modificable

,fecha,provincia,estado,departamento,carneros,ovejas,borregos,capones,corderos_corderas,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
0,2012-12-31,CHUBUT,MODIFICABLE,BIEDMA,2740,52320,22319,25489,29517,132385,478116.0,19.80,58.06,58.40,46.40,18.10,12.40,6.70
3,2015-12-31,CHUBUT,MODIFICABLE,BIEDMA,3885,67528,28319,33296,38117,171145,672480.0,18.58,58.18,58.70,114.20,22.20,15.80,10.20
4,2016-12-31,CHUBUT,MODIFICABLE,BIEDMA,3743,70451,30050,33038,37923,175205,653800.0,17.99,59.93,57.50,88.90,25.20,18.60,12.90
5,2017-12-31,CHUBUT,MODIFICABLE,BIEDMA,3900,71790,32259,34024,37889,179862,653800.0,19.73,58.95,55.80,291.90,19.10,13.60,8.40
6,2018-12-31,CHUBUT,MODIFICABLE,BIEDMA,4070,70696,32886,34339,39118,181109,653800.0,18.86,58.89,56.30,99.00,21.00,14.80,9.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,2016-12-31,CHUBUT,MODIFICABLE,TELSEN,4711,74125,28715,31728,31883,171162,637000.0,20.20,53.55,50.80,273.33,17.47,11.57,5.77
160,2017-12-31,CHUBUT,MODIFICABLE,TELSEN,4496,71149,27574,28606,31987,163812,637000.0,19.11,56.01,47.17,220.03,16.60,10.93,5.03
161,2018-12-31,CHUBUT,MODIFICABLE,TELSEN,4634,74179,28793,35979,28221,171806,637000.0,20.38,54.64,47.93,201.40,17.63,11.33,5.03
162,2019-12-31,CHUBUT,MODIFICABLE,TELSEN,4305,72515,27648,35273,29417,169158,613021.5,16.88,53.83,47.57,119.47,17.53,11.17,4.83
163,2020-12-31,CHUBUT,MODIFICABLE,TELSEN,4416,70736,27084,31418,30062,163716,614250.0,21.55,52.96,46.63,101.47,16.60,10.60,4.63

Lo siguiente es concatenar los dos dataset: el de datos reales y el de datos modificables para obtener un nuevo Dataset actualizado.

In [31]:
df_actualizado = pd.concat([df_real, df_modificable])
df_actualizado

,fecha,provincia,estado,departamento,carneros,ovejas,borregos,capones,corderos_corderas,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
1,2013-12-31,CHUBUT,REAL,BIEDMA,3925,70677,27227,33389,36961,172179,544941.0,19.80,55.00,64.70,226.50,19.90,14.20,8.80
2,2014-12-31,CHUBUT,REAL,BIEDMA,3223,61195,29491,29688,34926,158523,513951.0,19.22,58.86,60.50,331.30,20.60,14.70,9.20
16,2013-12-31,CHUBUT,REAL,CUSHAMEN,4751,85946,26255,17619,41451,176022,479996.0,20.04,57.47,58.22,769.59,18.90,11.88,5.49
17,2014-12-31,CHUBUT,REAL,CUSHAMEN,4198,77263,26512,18975,46290,173238,578184.0,19.74,63.35,59.10,640.40,17.03,10.46,4.62
28,2013-12-31,CHUBUT,REAL,FLORENTINO AMEGHINO,9114,150199,71752,55841,95320,382226,1088145.0,19.30,57.75,55.10,135.50,18.30,11.80,5.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,2016-12-31,CHUBUT,MODIFICABLE,TELSEN,4711,74125,28715,31728,31883,171162,637000.0,20.20,53.55,50.80,273.33,17.47,11.57,5.77
160,2017-12-31,CHUBUT,MODIFICABLE,TELSEN,4496,71149,27574,28606,31987,163812,637000.0,19.11,56.01,47.17,220.03,16.60,10.93,5.03
161,2018-12-31,CHUBUT,MODIFICABLE,TELSEN,4634,74179,28793,35979,28221,171806,637000.0,20.38,54.64,47.93,201.40,17.63,11.33,5.03
162,2019-12-31,CHUBUT,MODIFICABLE,TELSEN,4305,72515,27648,35273,29417,169158,613021.5,16.88,53.83,47.57,119.47,17.53,11.17,4.83
163,2020-12-31,CHUBUT,MODIFICABLE,TELSEN,4416,70736,27084,31418,30062,163716,614250.0,21.55,52.96,46.63,101.47,16.60,10.60,4.63

Luego ordenamos el Data frame por el índice.

In [32]:
df_ordenado = df_actualizado.sort_index()
df_ordenado

,fecha,provincia,estado,departamento,carneros,ovejas,borregos,capones,corderos_corderas,total_ovinos,kilos_lana,finura,rinde,humedad,cant_lluvia,tem_max,temp_media,temp_min
0,2012-12-31,CHUBUT,MODIFICABLE,BIEDMA,2740,52320,22319,25489,29517,132385,478116.0,19.80,58.06,58.40,46.40,18.10,12.40,6.70
1,2013-12-31,CHUBUT,REAL,BIEDMA,3925,70677,27227,33389,36961,172179,544941.0,19.80,55.00,64.70,226.50,19.90,14.20,8.80
2,2014-12-31,CHUBUT,REAL,BIEDMA,3223,61195,29491,29688,34926,158523,513951.0,19.22,58.86,60.50,331.30,20.60,14.70,9.20
3,2015-12-31,CHUBUT,MODIFICABLE,BIEDMA,3885,67528,28319,33296,38117,171145,672480.0,18.58,58.18,58.70,114.20,22.20,15.80,10.20
4,2016-12-31,CHUBUT,MODIFICABLE,BIEDMA,3743,70451,30050,33038,37923,175205,653800.0,17.99,59.93,57.50,88.90,25.20,18.60,12.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,2016-12-31,CHUBUT,MODIFICABLE,TELSEN,4711,74125,28715,31728,31883,171162,637000.0,20.20,53.55,50.80,273.33,17.47,11.57,5.77
160,2017-12-31,CHUBUT,MODIFICABLE,TELSEN,4496,71149,27574,28606,31987,163812,637000.0,19.11,56.01,47.17,220.03,16.60,10.93,5.03
161,2018-12-31,CHUBUT,MODIFICABLE,TELSEN,4634,74179,28793,35979,28221,171806,637000.0,20.38,54.64,47.93,201.40,17.63,11.33,5.03
162,2019-12-31,CHUBUT,MODIFICABLE,TELSEN,4305,72515,27648,35273,29417,169158,613021.5,16.88,53.83,47.57,119.47,17.53,11.17,4.83
163,2020-12-31,CHUBUT,MODIFICABLE,TELSEN,4416,70736,27084,31418,30062,163716,614250.0,21.55,52.96,46.63,101.47,16.60,10.60,4.63

Y finalmente guardamos el resultado en un archivo csv.

In [33]:
df_ordenado.to_csv("dataset_aplicado_%_existencias.csv", index=False)